### ISSUE TITLE
Case studies and feature extraction node

### ISSUE THREAD

**Issue by XuMa369** [ucsdwcsng/wiros_processing_node#2]
In your paper writed “The corresponding Python3 scripts to get started with WiROS and these case studies are provided within the ‘Feature-extraction’ node.”,but I am not find ‘Feature-extraction’ node on github.

**Comment by XuMa369** [comment]
Hello, I am very interested in case A "Localization to combat Kidnapped Robot Problem" in your paper, but I did not find the source code on github, if you can please send the source code to my email(1725dev@gmail.com), I would be very grateful

**Comment by wshunter** [comment]
Hey, I'll upload the case studies later today. Thanks for your interest in the project,

**Comment by XuMa369** [comment]
> Hey, I'll upload the case studies later today. Thanks for your interest in the project,

Thank you very much

**Comment by wshunter** [comment]
Hey, I've uploaded the case study you referenced. I'll add another case study shortly using P2SLAM, since I think that might be more useful to you if you're looking at robotics applications. If you have any questions about the code or the project in general, you can also email me at wshunter@ucsd.edu . I'll leave this open for the meantime until I upload the rest of the case studies.
